---
version: "3.9"

services:
  test_files:
    build:
      context: .
      dockerfile: Dockerfile.test_files
      network: ${NETWORK:-default}
    volumes: [tests:/tests]

  auth-proxy:
    image: quay.io/mojanalytics/auth-proxy:v5.2.6
    ports: [3000:3000]
    environment:
      USER: ${GITHUB_USER:-rstudio}
      TARGET_URL: http://rstudio:8787
      AUTH0_CALLBACK_URL: http://localhost:3000/callback
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      COOKIE_MAXAGE: "28800"
      COOKIE_SECRET: ${COOKIE_SECRET}
      RSTUDIO_ADD_SECURE_COOKIE: "true"
      RSTUDIO_SECURE_COOKIE_KEY: "8865825c306d4bd1a90c505dcde189fb"

  rstudio:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      network: ${NETWORK:-default}
    ports: [8787:8787]
    network_mode: ${NETWORK:-default}
    volumes: [tests:/share/tests:ro]
    depends_on: [auth-proxy]
    environment:
      SECURE_COOKIE_KEY: "8865825c306d4bd1a90c505dcde189fb"
      AWS_DEFAULT_REGION: "eu-west-1"

  inspec:
    image: chef/inspec:current
    network_mode: ${NETWORK}
    environment: { CHEF_LICENSE: accept-no-persist }
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tests:/share/tests:ro

volumes:
  tests:
