---
version: "3.7"

services:
  test_files:
    build:
      context: .
      dockerfile: Dockerfile.test_files
      network: ${NETWORK:-default}
    volumes: [tests:/tests]

  auth-proxy:
    image: quay.io/mojanalytics/auth-proxy:v5.2.6
    ports: [3000:3000]
    environment:
      USER: rstudio
      AUTH0_CALLBACK_URL: https://0.0.0.0/callback
      AUTH0_CLIENT_ID: foobarbazbam
      AUTH0_CLIENT_SECRET: z-010be6c0-50fa-11eb-ae93-0242ac130002
      AUTH0_DOMAIN: test.eu.auth0.com
      COOKIE_MAXAGE: "28800"
      COOKIE_SECRET: 5af47df8145b44cbabdfb5bd533fb9a1
      RSTUDIO_ADD_SECURE_COOKIE: "true"
      RSTUDIO_SECURE_COOKIE_KEY: 8865825c306d4bd1a90c505dcde189fb
      TARGET_URL: http://0.0.0.0:8787

  test:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    ports: [8787:8787]
    network_mode: ${NETWORK}
    volumes: [tests:/share/tests:ro]
    depends_on: [auth-proxy]
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_REGION: eu-west-1
      SECURE_COOKIE_KEY: 8865825c306d4bd1a90c505dcde189fb
  inspec:
    image: chef/inspec:current
    network_mode: ${NETWORK}
    environment: { CHEF_LICENSE: accept-no-persist }
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tests:/share/tests:ro

volumes:
  tests:
