---
version: "3.7"

services:
  test_files:
    build:
      context: .
      dockerfile: Dockerfile.test_files
      network: ${NETWORK:-default}
    volumes:
      - tests:/tests
  test:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG:-latest}
    ports: [8787:8787]
    network_mode: ${NETWORK}
    volumes:
      - tests:/share/tests:ro
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_REGION: eu-west-1
  inspec:
    image: chef/inspec:current
    network_mode: ${NETWORK}
    environment:
      CHEF_LICENSE: accept-no-persist
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tests:/share/tests:ro

volumes:
  tests:
