---
version: "3.9"

services:
  test_files:
    build:
      context: .
      dockerfile: Dockerfile.test_files
      network: ${NETWORK:-default}
    volumes: [tests:/tests]

  nginx-proxy:
    image: ${REGISTRY}/nginx-proxy:0.2.0
    ports: [80:3000]
    build:
      network: ${NETWORK:-default}
      context: .
    environment:
      APP_PORT: "8787"
      APP_HOST: "rstudio"
      AUTH0_TENANT_DOMAIN: ${AUTH0_TENANT_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      LOGOUT_URL: ${LOGOUT_URL}
      USERNAME: ${USERNAME}
      REDIRECT_DOMAIN: "tools.alpha.mojanalytics.xyz"
      ANALYTICAL_PLATFORM_TOOL: "rstudio"

  rstudio:
    image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      network: ${NETWORK:-default}
    ports: [8787:8787]
    network_mode: ${NETWORK:-default}
    volumes: [tests:/share/tests:ro]
    depends_on: [nginx-proxy]
    environment:
      SECURE_COOKIE_KEY: "8865825c306d4bd1a90c505dcde189fb"
      AWS_DEFAULT_REGION: "eu-west-1"

  inspec:
    image: chef/inspec:current
    network_mode: ${NETWORK}
    environment: { CHEF_LICENSE: accept-no-persist }
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tests:/share/tests:ro

volumes:
  tests:
