---
name: RStudio Build & Test

"on":
  pull_request:
  push: { branches: [main] }

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yaml Lint
        uses: actionshub/yamllint@master

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@master

  docker:
    needs: [mdl, yamllint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Install Inspec
        uses: actionshub/chef-install@1.1.0
        with: { project: inspec }
      - name: Test
        run: make test
        env: { CHEF_LICENSE: accept-no-persist }
