name: Sync Fork

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        if: ${{ github.repo.name == ministryofjustice/analytics-platform-rstudio-public }}
        with:
          source_repo: "https://${{ secrets.ACCESS_TOKEN }}@github.com/ministryofjustice/analytics-platform-rstudio.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
