---
name: Repo Sync

"on":
  push:
    branches: [main]

jobs:
  repo-sync:
    name: Repo Sync
    if: ${{ github.repository }} == 'analytics-platform-rstudio'
    runs-on: ubuntu-latest
    steps:
      - name: Sync main branch to public fork
        uses: wei/git-sync@v2
        with:
          source_repo: "${{ secrets.SOURCE_REPO }}"
          source_branch: "main"
          destination_repo: "ministryofjustice/analytics-platform-rstudio-public"
          destination_branch: "main"
